import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"]
})


export const metadata: Metadata = {
  title: "Dev_Red_Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={"dark overflow-x-hidden" + " " + outfit.className} // Space at the end of string is required
      >

        {children}
      </body>
    </html>
  );
}
